setup:
    prefix: 'j2s7s300_driver'
    model_filename: "jaco_dynamics"
    object_centers: {'HUMAN_CENTER': [-0.6,-0.55,0.0], 'LAPTOP_CENTER': [-0.7929,-0.1,0.0]}
    feat_list: ['efficiency']
    feat_weights: [1.0]
    start: [180.0, 160.0, 175.0, 40.0, 275.0, 180.0, 280.0]
    goals: [
        [160.0, 90.0, 180.0, 160.0, 270.0, 180.0, 280.0],
        [200.0, 90.0, 180.0, 160.0, 270.0, 180.0, 280.0]
    ]
    #goal_poses: [
    #    [-0.8, -0.3, 0.5],
    #    [-0.8, 0.3, 0.5]
    #]
    T: 20.0
    timestep: 0.5
    save_dir: "/data/teleoperation/"

planner:
    # These settings have been tuned for trajopt planner.
    type: "trajopt"
    max_iter: 50
    num_waypts: 5

controller:
    # These settings have been tuned for PID controller.
    type: "pid"
    p_gain: 0.5
    i_gain: 0.0
    d_gain: 0.1
    epsilon: 0.10
    max_cmd: 40.0

learner:
    betas: [1]
    belief: [0.5, 0.5]
